/**
 * Animation type flag: Generated by a vertical offset of the background.
 * @constant {number}
 */
export const ANIMATION_VERTICAL = 1;
/**
 * Animation type flag: Generated by a horizontal offset of the background.
 * @constant {number}
 */
export const ANIMATION_HORIZONTAL = 2;
/**
 * Animation type flag: Played only once (else looping indefinitely).
 * @constant {number}
 */
export const ANIMATION_ONCE = 4;
/**
 * Animation type flag: A callback is executed at the end of a cycle.
 * @constant {number}
 */
export const ANIMATION_CALLBACK = 8;
/**
 * Animation type flag: At the last frame of the animation it reverses (if used in conjunction with ONCE it will have no effect).
 * @constant {number}
 */
export const ANIMATION_PINGPONG = 32;

/**
 * Default properties for Animation instances.
 * @type {Object}
 */
const defaults = {
    // The url of the image to be used as an animation or sprite
    imageURL : null,
    // The number of frames to be displayed when playing the animation
    numberOfFrame : 1,
    // The distance in pixels between two frames
    delta : 0,
    // The rate at which the frames change in miliseconds
    refreshRate : 30,
    // The type of the animation.This is a bitwise OR of the properties.
    type : 0,
    // The x coordinate where the first sprite begins
    offsetX : 0,
    // The y coordinate where the first sprite begins
    offsetY : 0
};

/**
 * Animation class for managing sprite sheet animations.
 * @class Animation
 */
class Animation {
    /**
     * Creates an instance of Animation.
     * @param {Object} options - Configuration options for the animation.
     * @param {string} [options.imageURL=null] - The URL of the image to be used as an animation or sprite.
     * @param {number} [options.numberOfFrame=1] - The number of frames to be displayed when playing the animation.
     * @param {number} [options.delta=0] - The distance in pixels between two frames.
     * @param {number} [options.refreshRate=30] - The rate at which the frames change in milliseconds.
     * @param {number} [options.type=0] - The type of the animation. This is a bitwise OR of the animation type flags.
     * @param {number} [options.offsetX=0] - The x coordinate where the first sprite begins.
     * @param {number} [options.offsetY=0] - The y coordinate where the first sprite begins.
     */
    constructor(options) {
        Object.keys(defaults).forEach((key) => {
            if (key in options) this[key] = options[key];
        });
    }

    /**
     * Loads the animation image from the specified URL.
     * @returns {Promise} Promise that resolves when the image is loaded.
     */
    load() {
        this.img = new Image();
        this.img.src = this.imageURL;

        return new Promise((resolve) => {
            this.img.addEventListener('load', resolve);
        });
    }

    /**
     * Checks if the animation image has finished loading.
     * @returns {boolean} True if the image is complete, false otherwise.
     */
    isReady() {
        return this.img.complete;
    }
}

Object.assign(Animation.prototype, defaults);

export default Animation;
